import numpy as np
from math import floor
# Armchair graphene nanoribbon supercell
class agnr:
    def __init__(self, name, N_dimers, config, include_H, backend):
        self.name = name

        self.n_C = 2*N_dimers # Number of carbon atoms
        if include_H: # Terminate dangling edge bonds with hydrogen
            self.n_H = 4
        else:
            self.n_H = 0
        self.n_atoms = self.n_C + self.n_H # Total number of atoms
        self.n_valence = int((4*self.n_C + self.n_H)/2) # Number of valence bands generated by pseudopotential method

        # Atomic radii
        self.atom_rad = backend.xp.ones(self.n_atoms)
        self.atom_rad[0:self.n_C] = config.r_C

        # Unit vectors
        x_hat = backend.xp.array([1, 0, 0]) # Unit vector along ribbon length
        y_hat = backend.xp.array([0, 1, 0]) # Unit vector along ribbon width
        a_hat = backend.xp.array([1/2, np.sqrt(3)/2, 0]) # Unit vector of primitive cell

        # Generate atom positions, starting with carbon
        self.atom_pos = backend.xp.zeros((self.n_atoms, 3))
        # Starting primitive cell
        self.atom_pos[1, :] = config.a_CC * a_hat
        self.atom_pos[2, :] = self.atom_pos[1, :] + config.a_CC * x_hat
        self.atom_pos[3, :] = self.atom_pos[0, :] + 2 * config.a_CC * x_hat
        for d in range(floor(N_dimers/2 - 1)): # Loop over whole primitive cells along ribbon width
            for n in range(4): # Loop over atoms within primitive cell
                self.atom_pos[4*(d+1)+n, :] = self.atom_pos[n, :] + (d+1) * np.sqrt(3) * config.a_CC * y_hat
        if N_dimers/2 % 1 > 0: # Add a half primitive cell along ribbon width
            self.atom_pos[self.n_C-2, :] = self.atom_pos[0, :] + floor(N_dimers/2) * np.sqrt(3) * config.a_CC * y_hat
            self.atom_pos[self.n_C-1, :] = self.atom_pos[3, :] + floor(N_dimers/2) * np.sqrt(3) * config.a_CC * y_hat
        if self.n_H > 0: # Terminate dangling bonds
            self.atom_pos[self.n_C, :] = self.atom_pos[0, :] + config.a_CH * (x_hat - a_hat)
            self.atom_pos[self.n_C+1, :] = self.atom_pos[3, :] + config.a_CH * (-a_hat)
            self.atom_pos[self.n_C+2, :] = (N_dimers/2 % 1 > 0) * (self.atom_pos[0, :] + floor(N_dimers/2) * np.sqrt(3) * config.a_CC * y_hat + config.a_CH * a_hat) + (N_dimers/2 % 1 == 0) * (self.atom_pos[1, :] + floor(N_dimers/2 - 1) * np.sqrt(3) * config.a_CC * y_hat + config.a_CH * (a_hat - x_hat))
            self.atom_pos[self.n_C+3, :] = (N_dimers/2 % 1 > 0) * (self.atom_pos[3, :] + floor(N_dimers/2) * np.sqrt(3) * config.a_CC * y_hat + config.a_CH * (a_hat - x_hat)) + (N_dimers/2 % 1 == 0) * (self.atom_pos[2, :] + floor(N_dimers/2 - 1) * np.sqrt(3) * config.a_CC * y_hat + config.a_CH * a_hat)
        self.atom_pos = self.atom_pos - backend.xp.ones_like(self.atom_pos) * backend.xp.average(self.atom_pos, axis=0) # Shift coordinate origin to center

        # Generators of superlattice vectors
        if backend.name == "cupy":
            self.R_gen = backend.xp.array([[3 * config.a_CC, 0, 0],
                                [0, (np.max(self.atom_pos[:, 1] - np.min(self.atom_pos[:, 1]))).get() + config.N_y, 0],
                                [0, 0, config.N_z]])
        else:
            self.R_gen = backend.xp.array([[3 * config.a_CC, 0, 0],
                                [0, (np.max(self.atom_pos[:, 1] - np.min(self.atom_pos[:, 1]))) + config.N_y, 0],
                                [0, 0, config.N_z]])
        self.V_cell = backend.xp.dot(backend.xp.cross(self.R_gen[0, :], self.R_gen[1, :]), self.R_gen[2, :]) # Supercell volume

        # Reciprocal space points
        k_x = np.linspace(0, np.pi/backend.xp.linalg.norm(self.R_gen[0, :]), config.n_k)
        self.k = backend.xp.array([k_x, np.zeros_like(k_x), np.zeros_like(k_x)]).T
        self.k_label = r"$k_x \ (\pi/3a_{\mathrm{CC}})$"
        self.k_ticklabels = np.round(np.linspace(0, 1, 6), 1)
        self.k_ticks = config.n_k * self.k_ticklabels
