import numpy as np
from math import floor, gcd
# Carbon nanotube supercell
class cnt:
    def __init__(self, name, N_1, N_2, config, include_H, backend):
        self.name = name

        # Unit vectors
        x_hat = backend.xp.array([1, 0, 0]) # Axial unit vector
        y_hat = backend.xp.array([0, 1, 0])
        z_hat = backend.xp.array([0, 0, 1])
        a_hat = backend.xp.array([1/2, np.sqrt(3)/2, 0]) # Unit vector of primitive cell in graphene
        R_graphene = np.sqrt(3) * config.a_CC * backend.xp.array([a_hat, a_hat - x_hat]) # Primitive lattice vectors of graphene
        if backend.name == "cupy":
            r_hat = lambda phi: backend.xp.array([0, backend.xp.cos(phi).get(), backend.xp.sin(phi).get()]) # Radial unit vector as a function of aximuthal angle
            R = lambda theta: backend.xp.array([[1, 0, 0],
                                        [0, backend.xp.cos(theta).get(), backend.xp.sin(theta).get()],
                                        [0, -backend.xp.sin(theta).get(), backend.xp.cos(theta).get()]]) # Matrix of rotations about tube axis by angle theta
        else:
            r_hat = lambda phi: backend.xp.array([0, np.cos(phi), np.sin(phi)]) # Radial unit vector as a function of aximuthal angle
            R = lambda theta: backend.xp.array([[1, 0, 0],
                                        [0, np.cos(theta), np.sin(theta)],
                                        [0, -np.sin(theta), np.cos(theta)]]) # Matrix of rotations about tube axis by angle theta
        
        # Chiral nanotube coordinate operations
        GCD = gcd(N_1, N_2)
        n = ((N_1 - N_2) % (3 * GCD) == 0) * 3 * GCD + ((N_1 - N_2) % (3 * GCD) != 0) * GCD
        C = N_1 * R_graphene[0, :] + N_2 * R_graphene[1, :] # Wrapping vector within graphene plane
        L = np.sqrt(3) / n * backend.xp.cross(z_hat, C) # Axial period within graphene plane
        h = lambda d: backend.xp.sign(backend.xp.dot(d, y_hat)) * backend.xp.linalg.norm(backend.xp.cross(d, C)) / backend.xp.linalg.norm(C) # Primitive helical translation (axial)
        N_L = int(backend.xp.absolute(backend.xp.round(backend.xp.linalg.norm(L) / h(backend.xp.sum(R_graphene, axis=0))))) # Number of axial translations in period
        phi = lambda d: 2 * np.pi * backend.xp.dot(d, C) / (backend.xp.linalg.norm(C)**2) # Mapping from two-atom separation in graphene to helical rotation
        S = lambda tau, d: R(phi(d)) @ tau + h(d) * x_hat # Screw operation mapping translation d relative to tau from planar graphene onto nanotube

        # Generate atom positions, starting with carbon
        self.n_C = int(2 * GCD * N_L * config.N_a) # Number of carbon atoms
        if include_H: # Terminate dangling edge bonds with hydrogen
            self.n_H = 6 * GCD * (config.N_x > 0)
        else:
            self.n_H = 0
        self.n_atoms = self.n_C + self.n_H # Total number of carbon and hydrogen atoms
        self.n_valence = int((4*self.n_C + self.n_H)/2) # Number of valence bands generated by pseudopotential method

        # Atomic radii
        self.atom_rad = backend.xp.ones(self.n_atoms)
        self.atom_rad[0:self.n_C] = config.r_C

        self.atom_pos = backend.xp.zeros((self.n_atoms, 3))
        idx_C = 0; # Number of carbon atoms counted so far
        self.atom_pos[0, :] = backend.xp.linalg.norm(C) / (2 * np.pi) * y_hat
        for a in range(floor(config.N_a)):
            for l in range(N_L):
                for r in range(GCD):
                    self.atom_pos[idx_C, :] = R(2 * np.pi * r / GCD) @ S(self.atom_pos[0, :], l * backend.xp.sum(R_graphene, axis=0)) + a * backend.xp.linalg.norm(L) * x_hat
                    self.atom_pos[idx_C+1, :] = S(self.atom_pos[idx_C, :], backend.xp.sum(R_graphene, axis=0)/3)
                    idx_C = idx_C + 2
        if config.N_a % 1 > 0: # Add a half motif along circumference
            for t in range(idx_C / (2 * floor(config.N_a))):
                self.atom_pos[idx_C, :] = self.atom_pos[t, :] + floor(config.N_a) * backend.xp.linalg.norm(L) * x_hat
                idx_C = idx_C + 1

        if self.n_H > 0:
            idx_H = 0 # Number of hydrogen atoms counted so far
            d_H = lambda d: config.a_CH * d / backend.xp.linalg.norm(d) # Separation between H and nearest C atoms
            for r in range(GCD):
                idx_H = idx_H
                '''
                tau(:,n_C+idx_H+1) = S(tau(:,2*r+1), d_H(a_1-2*(a_1+a_2)/3));
                tau(:,n_C+idx_H+2) = S(tau(:,n_C+idx_H+1), (1+a_CH/a_CC)*(a_1+a_2)/3);
                tau(:,n_C+idx_H+3) = S(tau(:,n_C+idx_H+1), (a_1+a_2));
                %tau(:,n_C+idx_H+3) = S( (mod(N_a,1)==0)*(tau(:,2*GCD*floor(N_a)*(N_L-1)+2*r+2)+floor(N_a-1)*N_L*vecnorm(L)*x_hat) + (mod(N_a,1)>0)*(tau(:,2*GCD+2*r+2)+floor(N_a)*N_L*vecnorm(L)*x_hat), d_H(a_1,1));
                idx_H = idx_H + 3; % (10,5) only
                '''

        self.atom_pos = self.atom_pos - backend.xp.ones_like(self.atom_pos) * backend.xp.average(self.atom_pos, axis=0) # Shift coordinate origin to center

        # Generators of superlattice vectors
        if backend.name == "cupy":
            self.R_gen = backend.xp.array([[(config.N_x > 0) * (backend.xp.max(self.atom_pos[:, 0] - backend.xp.min(self.atom_pos[:, 0])) + config.N_x).get() + (config.N_x == 0) * config.N_a * backend.xp.linalg.norm(L).get(), 0, 0],
                                [0, 2/np.pi * backend.xp.linalg.norm(C).get(), 0],
                                [0, 0, 2/np.pi * backend.xp.linalg.norm(C).get()]])
        else:
            self.R_gen = backend.xp.array([[(config.N_x > 0) * (backend.xp.max(self.atom_pos[:, 0] - backend.xp.min(self.atom_pos[:, 0])) + config.N_x) + (config.N_x == 0) * config.N_a * backend.xp.linalg.norm(L), 0, 0],
                                [0, 2/np.pi * backend.xp.linalg.norm(C), 0],
                                [0, 0, 2/np.pi * backend.xp.linalg.norm(C)]])
        self.V_cell = backend.xp.dot(backend.xp.cross(self.R_gen[0, :], self.R_gen[1, :]), self.R_gen[2, :]) # Supercell volume

        # Reciprocal space points
        k_x = np.linspace(0, np.pi/backend.xp.linalg.norm(self.R_gen[0, :]), config.n_k)
        self.k = backend.xp.array([k_x, np.zeros_like(k_x), np.zeros_like(k_x)]).T
        self.k_label = r"$k_x \ (\pi/a_x)$"
        self.k_ticklabels = np.round(np.linspace(0, 1, 6))
        self.k_ticks = config.n_k * self.k_ticklabels
