import numpy as np
from math import floor
# Graphene nanoribbon supercell
class gnr:
    def __init__(self, name, N_dimers_x, N_dimers_y, config, include_H, backend):
        self.name = name

        self.n_C = N_dimers_x * N_dimers_y # Number of carbon atoms
        if include_H: # Terminate dangling edge bonds with hydrogen
            self.n_H = (config.N_x > 0) * N_dimers_y + (config.N_y > 0) * 2 * N_dimers_x + (1 - (config.N_x == 0)) * (N_dimers_x/2 % 1 == 0) * (N_dimers_y/2 % 1 > 0)
        else:
            self.n_H = 0
        self.n_atoms = self.n_C + self.n_H # Total number of atoms
        self.n_valence = int((4*self.n_C + self.n_H)/2) # Number of valence bands generated by pseudopotential method

        # Atomic radii
        self.atom_rad = backend.xp.ones(self.n_atoms)
        self.atom_rad[0:self.n_C] = config.r_C

        # Unit vectors
        x_hat = backend.xp.array([1, 0, 0]) # Unit vector along ribbon length
        y_hat = backend.xp.array([0, 1, 0]) # Unit vector along ribbon width
        a_hat = backend.xp.array([1/2, np.sqrt(3)/2, 0]) # Unit vector of primitive cell

        # Generate atom positions, starting with carbon
        idx_C = 0 # Number of carbon atoms located so far
        self.atom_pos = backend.xp.zeros((self.n_atoms, 3))
        # Starting primitive cell
        self.atom_pos[1, :] = config.a_CC * a_hat
        self.atom_pos[2, :] = self.atom_pos[1, :] + config.a_CC * x_hat
        self.atom_pos[3, :] = self.atom_pos[0, :] + 2 * config.a_CC * x_hat
        for dx in range(floor(N_dimers_x/2)): # Loop over whole primitive cells along y axis
            for dy in range(floor(N_dimers_y/2)): # Loop over whole primitive cells along x axis
                for n in range(4): # Loop over atoms within primitive cell
                    self.atom_pos[idx_C, :] = self.atom_pos[n, :] + config.a_CC * (dx * 3 * x_hat + dy * backend.xp.sqrt(3) * y_hat)
                    idx_C = idx_C + 1
        if N_dimers_x/2 % 1 > 0: # Add floor(N_dimers_y) half primitive cells
            for dy in range(floor(N_dimers_y/2)):
                self.atom_pos[idx_C, :] = self.atom_pos[0, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + dy * backend.xp.sqrt(3) * y_hat)
                self.atom_pos[idx_C+1, :] = self.atom_pos[1, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + dy * backend.xp.sqrt(3) * y_hat)
                idx_C = idx_C + 2
        if N_dimers_y/2 % 1 > 0: # Add floor(N_dimers_x) half primitive cells
            for dx in range(floor(N_dimers_x/2)):
                self.atom_pos[idx_C, :] = self.atom_pos[0, :] + config.a_CC * (dx * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat)
                self.atom_pos[idx_C+1, :] = self.atom_pos[3, :] + config.a_CC * (dx * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat)
                idx_C = idx_C + 2
        if N_dimers_x/2 % 1 > 0 and N_dimers_y/2 % 1 > 0: # Add one atom to ribbon corner
            self.atom_pos[idx_C, :] = self.atom_pos[0, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat)
            idx_C = idx_C + 1

        if self.n_H > 0: # Terminate dangling bonds
            idx_H = 0 # Number of hydrogen atoms counted so far
            if config.N_x > 0:
                for dy in range(floor(N_dimers_y/2)):
                    self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[0, :] + dy * backend.xp.sqrt(3) * config.a_CC * y_hat + config.a_CH * (-x_hat)
                    self.atom_pos[self.n_C+idx_H+1, :] = (N_dimers_x/2 % 1 > 0) * (self.atom_pos[1, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + dy * np.sqrt(3) * y_hat)) + (N_dimers_x/2 % 1 == 0) * (self.atom_pos[3, :] + config.a_CC * ((N_dimers_x/2 - 1) * 3 * x_hat + dy * np.sqrt(3) * y_hat)) + config.a_CH * x_hat
                    idx_H = idx_H + 2
                if N_dimers_y/2 % 1 > 0: # Add one atom to ribbon corner
                    self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[0, :] + config.a_CC * floor(N_dimers_y/2) * np.sqrt(3) * y_hat + config.a_CH * (-x_hat)
                    idx_H = idx_H + 1
                    if N_dimers_x/2 % 1 == 0: # Add one atom to ribbon corner
                        self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[3, :] + config.a_CC * ((N_dimers_x/2 - 1) * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat) + config.a_CH * x_hat
                        idx_H = idx_H + 1
            if config.N_y > 0:
                for dx in range(floor(N_dimers_x/2)):
                    self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[0, :] + dx * 3 * config.a_CC * x_hat + config.a_CH * (x_hat - a_hat)
                    self.atom_pos[self.n_C+idx_H+1, :] = self.atom_pos[3, :] + dx * 3 * config.a_CC * x_hat + config.a_CH * (-a_hat)
                    self.atom_pos[self.n_C+idx_H+2, :] = (N_dimers_y/2 % 1 > 0) * (self.atom_pos[0, :] + config.a_CC * (dx * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat) + config.a_CH * a_hat) + (N_dimers_y/2 % 1 == 0) * (self.atom_pos[1, :] + config.a_CC * (dx * 3 * x_hat + (N_dimers_y/2 - 1) * np.sqrt(3) * y_hat) + config.a_CH * (a_hat - x_hat))
                    self.atom_pos[self.n_C+idx_H+3, :] = (N_dimers_y/2 % 1 > 0) * (self.atom_pos[3, :] + config.a_CC * (dx * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat) + config.a_CH * (a_hat - x_hat)) + (N_dimers_y/2 % 1 == 0) * (self.atom_pos[2, :] + config.a_CC * (dx * 3 * x_hat + (N_dimers_y/2 - 1) * np.sqrt(3) * y_hat) + config.a_CH * (a_hat))
                    idx_H = idx_H + 4
                if N_dimers_x/2 % 1 > 0: # Add one atom to ribbon corner
                    self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[0, :] + config.a_CC * floor(N_dimers_x/2) * 3 * x_hat + config.a_CH * (x_hat - a_hat)
                    idx_H = idx_H + 1
                    if N_dimers_y/2 % 1 == 0: # Add one atom to ribbon corner
                        self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[1, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + (N_dimers_y/2 - 1) * np.sqrt(3) * y_hat) + config.a_CH * (a_hat - x_hat)
                        idx_H = idx_H + 1
                    elif N_dimers_y/2 % 1 > 0: # Add one atom to ribbon corner
                        self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[0, :] + config.a_CC * (floor(N_dimers_x/2) * 3 * x_hat + floor(N_dimers_y/2) * np.sqrt(3) * y_hat) + config.a_CH * a_hat
                        idx_H = idx_H + 1
        
        self.atom_pos = self.atom_pos - backend.xp.ones_like(self.atom_pos) * backend.xp.average(self.atom_pos, axis=0) # Shift coordinate origin to center

        # Generators of superlattice vectors
        if backend.name == "cupy":
            self.R_gen = backend.xp.array([[(backend.xp.max(self.atom_pos[:, 0]) - backend.xp.min(self.atom_pos[:, 0])).get() + (config.N_x == 0) * config.a_CC + config.N_x, 0, 0],
                                [0, (backend.xp.max(self.atom_pos[:, 1] - backend.xp.min(self.atom_pos[:, 1]))).get() + (config.N_y == 0) * np.sqrt(3)/2 * config.a_CC + config.N_y, 0],
                                [0, 0, config.N_z]])
        else: 
            self.R_gen = backend.xp.array([[(backend.xp.max(self.atom_pos[:, 0]) - backend.xp.min(self.atom_pos[:, 0])) + (config.N_x == 0) * config.a_CC + config.N_x, 0, 0],
                                [0, (backend.xp.max(self.atom_pos[:, 1] - backend.xp.min(self.atom_pos[:, 1]))) + (config.N_y == 0) * np.sqrt(3)/2 * config.a_CC + config.N_y, 0],
                                [0, 0, config.N_z]])
        self.V_cell = backend.xp.dot(backend.xp.cross(self.R_gen[0, :], self.R_gen[1, :]), self.R_gen[2, :]) # Supercell volume

        # Reciprocal space points
        k_x = np.linspace(0, np.pi/backend.xp.linalg.norm(self.R_gen[0, :]), config.n_k)
        self.k = backend.xp.array([k_x, np.zeros_like(k_x), np.zeros_like(k_x)]).T
        self.k_label = r"$k_x \ (\pi/a_x)$"
        self.k_ticklabels = np.round(np.linspace(0, 1, 6))
        self.k_ticks = config.n_k * self.k_ticklabels
        