import numpy as np
# Graphene supercell
class graphene:
    def __init__(self, config, backend):
        self.name = "Graphene"
        self.n_C = 2 # Number of carbon atoms
        self.n_H = 0 # Number of hydrogen atoms
        self.n_atoms = self.n_C + self.n_H # Total number of atoms
        self.n_valence = int((4*self.n_C + self.n_H)/2) # Number of valence bands generated by pseudopotential method
        self.atom_rad = config.r_C * backend.xp.ones(self.n_atoms) # Atomic radii

        # Generate atom positions
        self.atom_pos = backend.xp.zeros((self.n_atoms, 3))
        for i in range(self.n_atoms):
            self.atom_pos[i, 1] = config.a_CC * (-1/2 + i)

        # Generators of superlattice vectors
        self.R_gen = backend.xp.array([[np.sqrt(3)/2 * config.a_CC, 3/2 * config.a_CC, 0],
                                             [-np.sqrt(3)/2 * config.a_CC, 3/2 * config.a_CC, 0],
                                             [0, 0, config.N_z]])
        self.V_cell = backend.xp.dot(backend.xp.cross(self.R_gen[0, :], self.R_gen[1, :]), self.R_gen[2, :]) # Supercell volume

        # Reciprocal lattice points
        K = 4*np.pi/(3*np.sqrt(3)*config.a_CC) * backend.xp.array([1/2, np.sqrt(3)/2, 0])
        M = 2*np.pi/(3*config.a_CC) * backend.xp.array([0, 1, 0])
        D = backend.xp.sqrt(backend.xp.linalg.norm(K)**2 - backend.xp.linalg.norm(M)**2) * backend.xp.array([-1, 0, 0])
        n_pts = int(config.n_k/3)
        steps = np.linspace(0, 1, n_pts)
        steps_3D = backend.xp.array([steps, steps, steps]).T
        self.k = backend.xp.concatenate((-M * (steps_3D - backend.xp.ones_like(steps_3D)), 
                                         K * steps_3D, 
                                         D * steps_3D + K * backend.xp.ones_like(steps_3D)))
        self.k_ticks = np.array([0, n_pts-1, 2*n_pts-1, 3*n_pts-1])
        self.k_ticklabels = [r"$M$", r"$\Gamma$", r"$K$", r"$M$"]
        self.k_label = r"$k$"
