import numpy as np
from math import floor
# Zigzag carbon nanotube supercell
class zcnt:
    def __init__(self, name, N_1, config, include_H, backend):
        self.name = name

        self.n_C = int(4 * N_1 * config.N_a) # Number of carbon atoms
        if include_H: # Terminate dangling edge bonds with hydrogen
            self.n_H = 2 * N_1 * (config.N_x > 0)
        else:
            self.n_H = 0
        self.n_atoms = self.n_C + self.n_H # Total number of carbon and hydrogen atoms
        self.n_valence = int((4*self.n_C + self.n_H)/2) # Number of valence bands generated by pseudopotential method

        # Atomic radii
        self.atom_rad = backend.xp.ones(self.n_atoms)
        self.atom_rad[0:self.n_C] = config.r_C

        # Unit vectors
        x_hat = backend.xp.array([1, 0, 0]) # Axial unit vector
        a_hat = backend.xp.array([1/2, np.sqrt(3)/2, 0]) # Unit vector of primitive cell in graphene
        R_graphene = np.sqrt(3) * config.a_CC * backend.xp.array([a_hat, a_hat - x_hat]) # Primitive lattice vectors of graphene
        if backend.name == "cupy":
            r_hat = lambda phi: backend.xp.array([0, np.cos(phi).get(), np.sin(phi).get()]) # Radial unit vector as a function of aximuthal angle
        else:
            r_hat = lambda phi: backend.xp.array([0, np.cos(phi), np.sin(phi)]) # Radial unit vector as a function of aximuthal angle
        
        # Nanotube dimensions
        C = N_1 * R_graphene[0, :] # Wrapping vector
        r_tube = backend.xp.linalg.norm(C) / (2 * np.pi) # Nanotube radius
        theta = config.a_CC / r_tube # Characteristic angle of carbon-carbon bond

        # Generate atom positions, starting with carbon
        self.atom_pos = backend.xp.zeros((self.n_atoms, 3))
        idx_C = 0; # Number of carbon atoms counted so far
        for l in range(floor(config.N_a)):
            for c in range(N_1):
                self.atom_pos[idx_C, :] = r_tube * r_hat((c + 1/2) * np.sqrt(3) * theta) + l * 3 * config.a_CC * x_hat
                self.atom_pos[idx_C+1, :] = r_tube * r_hat(c * np.sqrt(3) * theta) + (l * 3 + 1/2) * config.a_CC * x_hat
                self.atom_pos[idx_C+2, :] = r_tube * r_hat(c * np.sqrt(3) * theta) + (l * 3 + 3/2) * config.a_CC * x_hat
                self.atom_pos[idx_C+3, :] = r_tube * r_hat((c + 1/2) * np.sqrt(3) * theta) + (l * 3 + 2) * config.a_CC * x_hat
                idx_C = idx_C + 4
        if config.N_a % 1 > 0: # Add a half motif along circumference
            for c in range(N_1):
                self.atom_pos[idx_C, :] = self.atom_pos[4*c, :] + floor(config.N_a) * 3 * config.a_CC * x_hat
                self.atom_pos[idx_C+1, :] = self.atom_pos[4*c+1, :] + floor(config.N_a) * 3 * config.a_CC * x_hat
                idx_C = idx_C + 2

        if self.n_H > 0:
            idx_H = 0 # Number of hydrogen atoms counted so far
            for c in range(N_1):
                self.atom_pos[self.n_C+idx_H, :] = self.atom_pos[4*c, :] + config.a_CH * (-x_hat)
                self.atom_pos[self.n_C+idx_H+1, :] = (config.N_a % 1 > 0) * (self.atom_pos[4*c+1, :] + (floor(config.N_a) * 3 * config.a_CC + config.a_CH) * x_hat) + (config.N_a % 1 == 0) * (self.atom_pos[4*c+3, :] + (floor(config.N_a - 1) * 3 * config.a_CC + config.a_CH) * x_hat)
                idx_H = idx_H + 2

        self.atom_pos = self.atom_pos - backend.xp.ones_like(self.atom_pos) * backend.xp.average(self.atom_pos, axis=0) # Shift coordinate origin to center

        # Generators of superlattice vectors
        if backend.name == "cupy":
            self.R_gen = backend.xp.array([[(backend.xp.max(self.atom_pos[:, 0] - backend.xp.min(self.atom_pos[:, 0]))).get() + (config.N_x == 0) * config.a_CC + config.N_x, 0, 0],
                                [0, 4*r_tube.get(), 0],
                                [0, 0, 4*r_tube.get()]])
        else:
            self.R_gen = backend.xp.array([[(backend.xp.max(self.atom_pos[:, 0] - backend.xp.min(self.atom_pos[:, 0]))) + (config.N_x == 0) * config.a_CC + config.N_x, 0, 0],
                                [0, 4*r_tube, 0],
                                [0, 0, 4*r_tube]])
        self.V_cell = backend.xp.dot(backend.xp.cross(self.R_gen[0, :], self.R_gen[1, :]), self.R_gen[2, :]) # Supercell volume

        # Reciprocal space points
        k_x = np.linspace(0, np.pi/backend.xp.linalg.norm(self.R_gen[0, :]), config.n_k)
        self.k = backend.xp.array([k_x, np.zeros_like(k_x), np.zeros_like(k_x)]).T
        self.k_label = r"$k_x \ (\pi/3a_{\mathrm{CC}})$"
        self.k_ticklabels = np.round(np.linspace(0, 1, 6), 1)
        self.k_ticks = config.n_k * self.k_ticklabels
